story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4app.urls')),
]

story4app/urls.py
from django.urls import path
from . import views

app_name = "story4app"

urlpatterns = [
	path('', views.home, name='home'),
    path('/project', views.project, name='project'),
    path('/story', views.story1, name='story')
]

story4app/models.py
from django.db import models

# Create your models here.

story4app/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'home.html')

def project(request):
	return render(request, 'project.html')

def story1(request):
	return render(request, 'story1.html')

story4app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lan="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    {% block style %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>
        {% block title %} {% endblock %}
    </title>

</head>

<body>

    <div class="container navbar">
        <header>
            <div class="logo">
                <h1>Jsaon</h1>
            </div>

            <nav>
                <ul>
                    <li><a href="#about">About Me</a></li>
                    <li><a href="#hobbies">Hobbies</a></li>
                    <li><a href="{% url 'story4app:project' %}">Project</a></li>
                    <li><a href="{% url 'story4app:story' %}">Profile</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </header>
    </div>


    {% block content %}
    {% endblock %}


    <footer>
        <div class="container contact" id="contact">
            <p>Mind send me a message? Sweet!</p>
        </div>
        <div class="container arrow">
            <a href="#">
                <img src="{% static 'img/arrow.png' %}" alt="pict error" width="25">
            </a>
        </div>
        <div class="container logo">
            <span><a href="https://www.linkedin.com/in/johanes-jason-155220195/" target="_blank">
                <img src="{% static 'img/LinkedIn Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://www.instagram.com/knightrexyz/" target="_blank">
                <img src="{% static 'img/IG Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://steamcommunity.com/id/jsaonn/" target="_blank">
                <img src="{% static 'img/Steam Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://gitlab.com/Jsaonn/" target="_blank">
                <img src="{% static 'img/Gitlab Logo.png' %}" alt="pict error" width="25">
            </a></span>
        </div>
    </footer>
</body>
</html>

story4app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}Jsaon's Web{% endblock %}


{% block content %}
    <div class="container homepage">
        <div class="text">
            <h1>
                <span>Hello there.</span>
                <br>
                <div>
                    <span>My name is</span>
                    <span class="name">J</span>
                    <span class="m-left name">s</span>
                    <span class="m-left name">a</span>
                    <span class="m-left name">o</span>
                    <span class="m-left name">n</span>
                    <span class="m-left name">,</span>
                </div>
                <br>
                <span>I'm a human.</span>
                <a href="#about">Explore more</a>
            </h1>
        </div>
    </div>

    <div class="container about" id="about">
        <div class="text-about">
            <h1>
                About me
            </h1>
        </div>
        <div class="about-me-text">
            <p>I called Jsaon, and I am second-year student of Computer Science at University of Indonesia.</p>
            <p>I usually read manga everyday, and I dedicated my life for sleep.</p>
        </div>
        <div class="profile-image">
            <img src="{% static 'img/Profile.png' %}" alt="This text is shown if server fails to load image" />
        </div>
    </div>

    <div class="container hobbies" id="hobbies">
        <div class="text-hobbies">
            <h1>Hobbies</h1>
        </div>
        <div class="hobbies-info">
            <div class="hobby">
                <img src="{% static 'img/FPS Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>FPS Games</h1></div>
            </div><br>
            <div class="hobby">
                <img src="{% static 'img/Psy Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>Psychology</h1></div>
            </div><br>
            <div class="hobby">
                <img src="{% static 'img/Sleep Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>Sleep</h1></div>
            </div>
        </div>
    </div>
{% endblock %}

story4app/templates/project.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}Jsaon's Project{% endblock %}

{% block content %}
        <div class="container coming-soon">
            <h1>Coming soon!</h1>
            <br>
            <a href="{% url 'story4app:home' %}">back</a>
        </div>
{% endblock %}

story4app/templates/story1.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<!-- <link rel="stylesheet" type="text/css"  href="{% static 'css/style2.css' %}"> -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
{% endblock %}

{% block title %}Story 1 PPW{% endblock %}


{% block content %}
    <div class="story1">
        <div>
            <h2 align="center">Welcome to my website!</h2>
        </div>

        <hr/>
        <br/>

        <div>
            <div>
                <div><img src="{% static 'img/pic1.jpg' %}" alt="pict error" class="rounded-circle" width="150"></div>
                <div class="text-black h3"><h3>Jaenhos Jsaon</h3></div>
            </div>
        </div><br/>

        <div>
            <h3>
                <div><b>About me :</b></div>
                <div>Second year student of Computer Science at Universitas Indonesia</div>
                <div>Passionate about psychology, mental development, and programming</div>
            </h3>
        </div><br/>

        <div>
            <h3>
                <b>Profile :</b>
                <ul>
                    <li>NPM 1906293120</li>
                    <li>Maung 2019</li>
                    <li>Computer Science, University of Indonesia</li>
                </ul>
            </h3>
        </div><br/>

        <div>
            <h3>
                <b>Hobbies :</b>
                <ul>
                    <li>Gaming</li>
                    <li>Sleep</li>
                </ul>
            </h3>
        </div><br/>

        <div>
            <h3>
            <div><b>Education :</b></div>
            <ul>
                <li>SMAN 13 Jakarta</li>
                <li>Universitas Indonesia</li>
            </ul>
            </h3>
        </div><br/>

        <div>
            <h3>
                <div><b>You can find me at :</b></div>
                <div>
                    <a href="https://www.instagram.com/knightrexyz/?hl=en" target="_blank">
                    <span><img src="{% static 'img/ig-logo.png' %}" alt="pict error" width="25"></span>
                    </a>
                    <a href="https://www.linkedin.com/in/johanes-jason-155220195/" target="_blank">
                    <span><img src="{% static 'img/linkedin-logo.png' %}" alt="pict error" width="25"></span>
                    </a>
                </div>
            </h3>
        </div>

        <div class="container back">
            <a href="{% url 'story4app:home' %}">back</a>
        </div>
    </div>
    {% endblock %}